name: Upload Code Coverage

on:
  push:
    branches:
      - main  # Change this to your main branch name if needed
  pull_request:

jobs:
  upload-coverage:
    name: Upload coverage report to Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: pytest --cov=./

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.COCOV }}
